package Vista;

import Controlador.ControladorAgendarCita;
import Controlador.ControladorAgregarMascota;
import Controlador.ControladorCrearCuenta;
import Controlador.ControladorHistorial;
import Controlador.ControladorMenuInicio;
import Controlador.ControladorMenuRecepcion;
import Controlador.ControladorModificarCliente;
import Controlador.ControladorRegistrarMascota;
import Controlador.ControladorVerCitasRecepcion;
import Controlador.ControladorVerMascotas;
import Excepciones.MascotaExcepcion;
import Modelo.VO.Cliente;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author danii
 */
public class VistaMenuRecepcion extends javax.swing.JDialog {

    /**
     * Creates new form Personal_1
     */
    public VistaMenuRecepcion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public VistaMenuRecepcion() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_registrarCliente = new javax.swing.JButton();
        btn_verCitas = new javax.swing.JButton();
        btn_agendarCita1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_cerrar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_registrarCliente.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_registrarCliente.setForeground(new java.awt.Color(0, 102, 255));
        btn_registrarCliente.setText("Registrar Cliente");
        btn_registrarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_registrarCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_registrarClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_registrarClienteFocusLost(evt);
            }
        });
        btn_registrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarClienteActionPerformed(evt);
            }
        });

        btn_verCitas.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_verCitas.setForeground(new java.awt.Color(0, 102, 255));
        btn_verCitas.setText("Ver citas");
        btn_verCitas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_verCitas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_verCitasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_verCitasFocusLost(evt);
            }
        });
        btn_verCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verCitasActionPerformed(evt);
            }
        });

        btn_agendarCita1.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_agendarCita1.setForeground(new java.awt.Color(0, 102, 255));
        btn_agendarCita1.setText("Agendar cita");
        btn_agendarCita1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_agendarCita1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_agendarCita1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_agendarCita1FocusLost(evt);
            }
        });
        btn_agendarCita1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendarCita1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_verCitas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_registrarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_agendarCita1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btn_registrarCliente)
                .addGap(42, 42, 42)
                .addComponent(btn_agendarCita1)
                .addGap(48, 48, 48)
                .addComponent(btn_verCitas)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 102, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modelo/Assets/recepcion.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("The munday free version", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("RECEPCION");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        btn_cerrar.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_cerrar.setForeground(new java.awt.Color(0, 102, 255));
        btn_cerrar.setText("Cerrar Sesion");
        btn_cerrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_cerrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_cerrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_cerrarFocusLost(evt);
            }
        });
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        btn_salir.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(0, 102, 255));
        btn_salir.setText("Salir");
        btn_salir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_salir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_salirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_salirFocusLost(evt);
            }
        });
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cerrar)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cerrar)
                    .addComponent(btn_salir))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        ControladorMenuRecepcion.salir();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        // TODO add your handling code here:
        ControladorMenuRecepcion.cerrarSesion();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_salirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_salirFocusGained
        // TODO add your handling code here:
        btn_salir.setBackground(new Color(102, 204, 255));
    }//GEN-LAST:event_btn_salirFocusGained

    private void btn_salirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_salirFocusLost
        // TODO add your handling code here:
        btn_salir.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btn_salirFocusLost

    private void btn_cerrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_cerrarFocusGained
        // TODO add your handling code here:
        btn_cerrar.setBackground(new Color(102, 204, 255));

    }//GEN-LAST:event_btn_cerrarFocusGained

    private void btn_cerrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_cerrarFocusLost
        // TODO add your handling code here
        btn_cerrar.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btn_cerrarFocusLost

    private void btn_registrarClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_registrarClienteFocusGained
        // TODO add your handling code here:
        btn_registrarCliente.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_btn_registrarClienteFocusGained

    private void btn_registrarClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_registrarClienteFocusLost
        // TODO add your handling code here:
        btn_registrarCliente.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_registrarClienteFocusLost

    private void btn_registrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarClienteActionPerformed
        // TODO add your handling code here:
        ControladorCrearCuenta.mostrarVentana(true);
    }//GEN-LAST:event_btn_registrarClienteActionPerformed

    private void btn_verCitasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_verCitasFocusGained
        // TODO add your handling code here:
        btn_verCitas.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_btn_verCitasFocusGained

    private void btn_verCitasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_verCitasFocusLost
        // TODO add your handling code here:
        btn_verCitas.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_verCitasFocusLost

    private void btn_verCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verCitasActionPerformed
        // TODO add your handling code here:
        ControladorVerCitasRecepcion.mostrarVentana();
    }//GEN-LAST:event_btn_verCitasActionPerformed

    private void btn_agendarCita1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_agendarCita1FocusGained
        // TODO add your handling code here:
        btn_agendarCita1.setBackground(new Color(102,153,255));
    }//GEN-LAST:event_btn_agendarCita1FocusGained

    private void btn_agendarCita1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_agendarCita1FocusLost
        // TODO add your handling code here:
        btn_agendarCita1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_agendarCita1FocusLost

    private void btn_agendarCita1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendarCita1ActionPerformed
        // TODO add your handling code here:
        ControladorMenuRecepcion.agendarCitaRec();
    }//GEN-LAST:event_btn_agendarCita1ActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setForeground(Color.magenta);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setForeground(new Color(0,102,204));
    }//GEN-LAST:event_jLabel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaMenuRecepcion dialog = new VistaMenuRecepcion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agendarCita1;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_registrarCliente;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_verCitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
