package Vista;

import Controlador.ControladorCrearCuenta;
import Controlador.ControladorInicioSesion;
import Excepciones.ClientesExcepciones;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author danii
 */
public class VistaInicioSesion extends javax.swing.JDialog {

    Image icon = Toolkit.getDefaultToolkit().getImage("/Modelo/Assets/usuario (3).png");

    /**
     * Creates new form Ventana_1
     */
    public VistaInicioSesion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        super.setIconImage(icon);
        initComponents();
    }

    public VistaInicioSesion() {
        super();
        super.setIconImage(icon);
        super.setTitle("Inicio sesion");

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_central = new javax.swing.JPanel();
        panel_inicio = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_salir = new javax.swing.JButton();
        btn_registro = new javax.swing.JButton();
        btn_inicio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        lbl_auxiliar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        avatar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logoN = new javax.swing.JLabel();
        animal = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_central.setBackground(new java.awt.Color(255, 255, 255));
        panel_central.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_inicio.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_salir.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(0, 51, 255));
        btn_salir.setText("Salir");
        btn_salir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_salir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_salirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_salirFocusLost(evt);
            }
        });
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir);

        btn_registro.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_registro.setForeground(new java.awt.Color(0, 51, 255));
        btn_registro.setText("Registrarte");
        btn_registro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_registro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_registroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_registroFocusLost(evt);
            }
        });
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registro);

        btn_inicio.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_inicio.setForeground(new java.awt.Color(0, 51, 255));
        btn_inicio.setText("Iniciar Sesion");
        btn_inicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_inicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_inicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_inicioFocusLost(evt);
            }
        });
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });
        jPanel1.add(btn_inicio);

        panel_inicio.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Usuario");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        txt_usuario.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(51, 51, 255));
        txt_usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_usuario.setDisabledTextColor(new java.awt.Color(51, 0, 255));
        txt_usuario.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        txt_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usuarioFocusLost(evt);
            }
        });
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Contraseña");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        txt_password.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        txt_password.setForeground(new java.awt.Color(51, 51, 255));
        txt_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passwordFocusLost(evt);
            }
        });
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 102, 255));
        jLabel5.setFont(new java.awt.Font("The munday free version", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("Bienvendio");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modelo/Assets/image 1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(avatar)
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_auxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(avatar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 20, Short.MAX_VALUE)
                .addComponent(lbl_auxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panel_inicio.add(jPanel2, java.awt.BorderLayout.CENTER);

        panel_central.add(panel_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 340, 420));

        jLabel1.setFont(new java.awt.Font("The munday free version", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("VETERINARIA");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        panel_central.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        logoN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modelo/Assets/image-Photoroom.png-Photoroom.png"))); // NOI18N
        panel_central.add(logoN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 150));

        animal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modelo/Assets/inicioAnimal (2).png"))); // NOI18N
        panel_central.add(animal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 270, 190));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modelo/Assets/fondoInicio.jpg"))); // NOI18N
        FONDO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_central.add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 420));

        getContentPane().add(panel_central, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ControladorCrearCuenta.mostrarVentana();
        txt_usuario.setText("");
        txt_password.setText("");

    }//GEN-LAST:event_btn_registroActionPerformed

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        try {
            // TODO add your handling code here:
            ControladorInicioSesion.iniciarSesion();
            txt_usuario.setText("");
            txt_password.setText("");
        } catch (SQLException ex) {
            System.out.println("EXCEPCION " + ex.getMessage());
        } catch (ClientesExcepciones ex) {
            System.out.println("EXCEPCION " + ex.getMessage());
        }
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
        txt_usuario.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        txt_password.requestFocus();


    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void txt_usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usuarioFocusGained
        // TODO add your handling code here:

        txt_usuario.setBackground(new Color(200, 228, 228));

    }//GEN-LAST:event_txt_usuarioFocusGained

    private void txt_usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usuarioFocusLost
        // TODO add your handling code here:
        txt_usuario.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_txt_usuarioFocusLost

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained
        // TODO add your handling code here:
        txt_password.setBackground(new Color(200, 228, 228));
    }//GEN-LAST:event_txt_passwordFocusGained

    private void txt_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusLost
        // TODO add your handling code here:
        txt_password.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_txt_passwordFocusLost

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                ControladorInicioSesion.iniciarSesion();
                txt_usuario.setText("");
                txt_password.setText("");
            } catch (SQLException ex) {
                System.out.println("EXCEPCION " + ex.getMessage());
            } catch (ClientesExcepciones ex) {
                lbl_auxiliar.setText("USUARIO NO ENCONTRADO");
                lbl_auxiliar.setVisible(true);
            }
        }
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:

        jLabel1.setForeground(new Color(204, 51, 255));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setForeground(new Color(01, 102, 255));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        jLabel5.setForeground(new Color(204, 51, 255));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        jLabel5.setForeground(new Color(01, 102, 255));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:

        jLabel2.setForeground(new Color(204, 51, 255));

    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel2.setForeground(new Color(01, 102, 255));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setForeground(new Color(204, 51, 255));

    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setForeground(new Color(01, 102, 255));
    }//GEN-LAST:event_jLabel3MouseExited

    private void btn_registroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_registroFocusGained
        // TODO add your handling code here:
        btn_registro.setBackground(new Color(187, 215, 243));
    }//GEN-LAST:event_btn_registroFocusGained

    private void btn_registroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_registroFocusLost
        // TODO add your handling code here:
        btn_registro.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_registroFocusLost

    private void btn_inicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_inicioFocusGained
        // TODO add your handling code here:
        btn_inicio.setBackground(new Color(187, 215, 243));
    }//GEN-LAST:event_btn_inicioFocusGained

    private void btn_inicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_inicioFocusLost
        // TODO add your handling code here:
        btn_inicio.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_inicioFocusLost

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
        btn_inicio.requestFocus();
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void btn_salirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_salirFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirFocusGained

    private void btn_salirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_salirFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirFocusLost

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    public JButton getBtn_inicio() {
        return btn_inicio;
    }

    public void setBtn_inicio(JButton btn_inicio) {
        this.btn_inicio = btn_inicio;
    }

    public JButton getBtn_registro() {
        return btn_registro;
    }

    public void setBtn_registro(JButton btn_registro) {
        this.btn_registro = btn_registro;
    }

    public JTextField getTxt_password() {
        return txt_password;
    }

    public void setTxt_password(JTextField txt_password) {
        this.txt_password = txt_password;
    }

    public JTextField getTxt_usuario() {
        return txt_usuario;
    }

    public void setTxt_usuario(JTextField txt_usuario) {
        this.txt_usuario = txt_usuario;
    }

    public JLabel getLbl_auxiliar() {
        return lbl_auxiliar;
    }

    public void setLbl_auxiliar(JLabel lbl_auxiliar) {
        this.lbl_auxiliar = lbl_auxiliar;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaInicioSesion dialog = new VistaInicioSesion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JLabel animal;
    private javax.swing.JLabel avatar;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_registro;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_auxiliar;
    private javax.swing.JLabel logoN;
    private javax.swing.JPanel panel_central;
    private javax.swing.JPanel panel_inicio;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
